/** Product prompt contract. Bump the version whenever output policy changes. */
export const CANONICAL_PROMPT_VERSION = 'canonical-character-v10';

/** Stable visual policy for Nano Banana 2.1's separate system instruction. */
export function buildCanonicalSystemPrompt(): string {
  return [
    'Create a consistent series of personalized, front-facing 3D cartoon character portraits from reference photographs.',
    'Use the same visual treatment in every image: a polished dimensional CG character sculpt, high-detail eyes, brows, lips, ears and facial planes; smooth skin with nuanced color variation and fine non-age-related material texture; layered volumetric hair with individually readable groups and strands; and natural material highlights.',
    'Use one soft directional studio key light with gentle fill, restrained shadows, and a plain light neutral background. Keep the level of detail, material finish, lighting, camera framing, and stylization consistent across subjects and retries.',
    'The reference photograph determines the person’s identity and adult or youth facial structure. Preserve recognizable head shape, facial proportions and facial maturity, but remove all visible skin wrinkles, dark circles and tired-looking discoloration beneath the eyes, and obvious signs of aging in every output. Preserve the person’s actual eye shape, eyelids, eye position and natural facial structure; do not erase identity-defining anatomy. Do not turn an adult into a child or substitute a generic attractive face. Apply only the explicitly requested under-20 exception to facial age in the edit instruction.',
    'Avoid flat vector illustration, cel shading, simplified color blocks, plastic skin, helmet-like hair, photorealism, and exaggerated cartoon proportions.',
  ].join(' ');
}

export function buildCanonicalPrompt(): string {
  return [
    'Transform the person in the provided photograph into one original stylized 3D cartoon character portrait.',
    'Preserve their recognizable identity with specific, accurate details: face shape, forehead, cheekbones, jaw and chin, eye spacing and shape, eyebrows, nose, lips, skin tone, hairline, hair color, hairstyle and texture, overall age range, and distinctive features. Keep any visible glasses or facial hair faithful to the photograph; do not reshape, average, or replace the person’s features.',
    'Pay special attention to the eyes as identity-defining features. Match the source person’s eye shape, size relative to the face, spacing, vertical position, natural tilt, eyelid opening and folds, brow-to-eye distance, and visible iris color. Keep both eyes naturally aligned and looking toward the camera while preserving real asymmetry. Do not enlarge, shift, over-round, or make the eyes generically cute or identical for attractiveness.',
    'Show exactly one person, facing the camera directly, with both eyes open and a very subtle natural closed-mouth smile. Lift the mouth corners only slightly; keep the cheeks and facial proportions close to a relaxed neutral expression. No teeth, open mouth, broad grin, or exaggerated expression.',
    'Treat the person’s facial structure and broad age category as part of their identity. Only if the person clearly appears younger than 20 years old, depict the same person a few years younger with a subtly fresher, rested look. If they appear 20 or older, or their age is uncertain, preserve adult facial maturity, facial fullness and proportions without making them childlike or generically youthful. For every age, remove all visible skin wrinkles and obvious aging signs: no forehead lines, crow’s feet, under-eye creases, mouth or neck wrinkles, age spots, sagging or crepey skin. Remove dark circles and tired-looking under-eye discoloration for every age, without changing the shape, size, spacing or natural contours of the eyes and eyelids. Preserve non-age-related distinctive marks and identity features.',
    'Include the complete three-dimensional head from the top of all hair through both ears and a small amount of neck. Keep the whole head inside the frame with generous margin; do not crop hair, ears, chin, or neck. Render natural visible ears where the hairstyle permits.',
    'Render the character in the consistent high-detail dimensional CG style specified above, with clear three-dimensional head volumes and carefully resolved eyelids, brows, nose, lips, ears, and facial hair where present. Preserve natural asymmetry and non-age-related distinctive marks instead of smoothing away identity. Keep clean contours and a front view consistent enough for later multi-view reconstruction.',
    'Give the wrinkle-free skin subtle region-specific color variation, softly modeled planes, and fine stylized non-aging surface texture that retains visible identity details from the photograph. Keep the rendering detailed without reintroducing wrinkles, age spots, under-eye dark circles or skin aging. Avoid a single flat skin color, airbrushed plastic skin, or invented freckles and marks. Where hair is present, render layered volumetric locks with readable strands, natural strand breakup, gentle root-to-tip tonal variation, and controlled highlights that follow the photographed hairstyle. Avoid a smooth helmet-like hair mass or a single flat hair color.',
    'Give the character a gently flattering, appealing look, slightly more attractive in presentation than a literal rendering of the photo. Use a soft directional key light with gentle fill and restrained shadows around the eyes, nose, ears, hair layers, and neck so the materials and forms remain legible. Keep the source person’s facial anatomy, skin tone, hair color, and distinctive features; do not replace them with a generic beauty ideal.',
    'Use a plain light neutral background. No scenery, props, extra people, body, text, logos, watermarks, speech bubbles, dramatic pose, or heavy shadows.',
    'Avoid photorealism, flat illustration, face-filter overlays, exaggerated caricature, and any recognizable studio or franchise style.',
  ].join(' ');
}
